[package]
name = "adventofcode2021"
version = "0.1.0"
edition = "2021"
default-run = "adventofcode2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
recap = "0.1"
serde = "1.0"
